### ISSUE TITLE
Keep getting Cloud not open HID device

### ISSUE THREAD

**Issue by kayintveen** [jamesridgway/devdeck#13]
Hi,

 keep getting StreamDeck.Transport.Transport.TransportError: Could not open HID device.
Tried disconnecting and reconnecting the deck also tried rebooting. 

Only other thing i noticed is that the log file keeps saying
2021-09-23 12:22:24,191 - devdeck - WARNING - No settings file detected!
2021-09-23 12:24:43,234 - devdeck - WARNING - No settings file detected!

Not sure how to continue

`2021-09-23 12:25:49,510 - devdeck - WARNING - No settings file detected!
Traceback (most recent call last):
  File "/usr/local/bin/devdeck", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/devdeck/main.py", line 48, in main
    deck.open()
  File "/usr/local/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeck.py", line 148, in open
    self.device.open()
  File "/usr/local/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 350, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/usr/local/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.`

**Comment by jamesridgway** [comment]
Can I just check that you have followed the installation instructions here:
https://github.com/jamesridgway/devdeck/wiki/Installation

**Comment by steoneill** [comment]
I'm seeing the same issue :
```
➜ ~ brew install hidapi
Warning: hidapi 0.11.2 is already installed and up-to-date.
To reinstall 0.11.2, run:
  brew reinstall hidapi
➜ ~ devdeck
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/devdeck", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/devdeck/main.py", line 40, in main
    streamdecks = DeviceManager().enumerate()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/StreamDeck/DeviceManager.py", line 89, in __init__
    self.transport = self._get_transport(transport)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/StreamDeck/DeviceManager.py", line 81, in _get_transport
    raise ProbeError("Probe failed to find any functional HID backend.", probe_errors)
StreamDeck.DeviceManager.ProbeError: ('Probe failed to find any functional HID backend.', {'libusb': TransportError("No suitable LibUSB HIDAPI library found on this system. Is the 'libhidapi.dylib' library installed?")})
➜ ~
```

**Comment by yuenesc** [comment]
Same issue I cannot run devdeck as it seems hidapi has not been found. Even after trying to install it with brew or ports, neither works on macOS Monterey 12.4

**Comment by chadwoodhead** [comment]
I'm also facing the same error on MacOS Monterey 12.4

**Comment by wrightbradley** [comment]
I am on MacOS Monterey 12.4 with M1 chip (don't really think the arch matters but adding it for troubleshooting data). I was able to get this working after uninstalling the Elgato Stream Deck software. With homebrew that command is: `brew uninstall --cask elgato-stream-deck`. Once that software was removed, devdeck ran successfully without the stacktrace mentioned [here](https://github.com/jamesridgway/devdeck/issues/13#issue-1005263461)

**Comment by chadwoodhead** [comment]
I got it working. Turns out the Stream Deck application can't be running when you run `devdeck`. I didn't realize devdeck was a replacement for the Stream Deck's regular application. Now that I understand that, it makes since I had to quit the Stream Deck app first. But that now leaves me at back to finding a Slack plugin for the Stream Deck that I can use with the native Stream Deck app. If anyone has any suggestion send them my way!

**Comment by wrightbradley** [comment]
@chadwoodhead I've been having some good success using the Slack keyboard shortcuts to handle various functions in Slack by using the Shortcuts Stream Deck plugin and Javascript/Applescript automation steps in custom Shortcuts I've built.
